require("dotenv").config();

module.exports = {
  EMAILJS_USER_ID: process.env.EMAILJS_USER_ID,
  EMAILJS_SERVICE_ID: process.env.EMAILJS_SERVICE_ID,
  EMAILJS_TEMPLATE_ID: process.env.EMAILJS_TEMPLATE_ID,

  EXTERNAL_APIS: {
    DOLLAR_QUOTE: process.env.DOLLAR_QUOTE_URL,
    UIT: process.env.UIT_URL,
    GOOGLE_NEWS: process.env.GOOGLE_NEWS_URL,
    GDELT_PROJECT: process.env.GDELT_PROJECT_URL,
    REDDIT_BASE_URL: process.env.REDDIT_BASE_URL,
  },
  HEADERS: {
    USER_AGENT: process.env.USER_AGENT,
    REDDIT_USER_AGENT: process.env.REDDIT_USER_AGENT,
  },

  COLLECTION_GRATITUDE: process.env.COLLECTION_GRATITUDE,
  COLLECTION_SECTION: process.env.COLLECTION_SECTION,
  COLLECTION_COUNTRIES: process.env.COLLECTION_COUNTRIES,
  COLLECTION_HOME_IMAGES: process.env.COLLECTION_HOME_IMAGES,

  FIREBASE_TYPE: process.env.FIREBASE_TYPE,
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_PRIVATE_KEY_ID: process.env.FIREBASE_PRIVATE_KEY_ID,
  FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g, "\n"),
  FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
  FIREBASE_CLIENT_ID: process.env.FIREBASE_CLIENT_ID,
  FIREBASE_AUTH_URI: process.env.FIREBASE_AUTH_URI,
  FIREBASE_TOKEN_URI: process.env.FIREBASE_TOKEN_URI,
  FIREBASE_AUTH_PROVIDER_X509_CERT_URL:
    process.env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
  FIREBASE_CLIENT_X509_CERT_URL: process.env.FIREBASE_CLIENT_X509_CERT_URL,
  FIREBASE_UNIVERSE_DOMAIN: process.env.FIREBASE_UNIVERSE_DOMAIN,
};
